name: selfish
channels:
  - pytorch
  - nvidia     
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pytorch
  - torchvision
  - torchaudio       
  - pytorch-cuda=12.1 
  - pip